name: PayloadHover_F450

defaults:
  # see https://hydra.cc/docs/advanced/overriding_packages/
  - /base/env_base@_here_
  - /base/sim_base@_here_
  # - /base/randomization_base@_here_

drone_model:
  name: hummingbird_f450 #hummingbird # hummingbird_f450
  controller: LeePositionController

time_encoding: false #true

############# Step 5: Real World Deployment #########################
sim:
  dt: 0.016  #TODO: 0.005, 0.016

env:
  num_envs: 1
  env_spacing: 6
  max_episode_length: 2000 #1500 #1000 #(default: 500)

trajectory_collection: false
domain_adaptation: false
fine_tuning: false  
real_deployment: ture

fictitious_force_gravity_ratio: 1.0 #0.7 #0.5 #0.3

# randomization:
#   drone:
#     train:
#       mass_scale: [1.2, 1.2]
#       inertia_scale: [1.2, 1.2]
#       c_tf_scale: [1.0, 1.0]
#       com: [0.02, 0.02]
# payload_mass_scale: [1.2, 1.2]
# bar_length: 1.1

randomization:
  drone:
    train:
      mass_scale: [1.2, 1.2]
      inertia_scale: [1.2, 1.2]
      c_tf_scale: [1.0, 1.0]
      com: [0.01, 0.01]
payload_mass_scale: [1.2, 1.2]
bar_length: 1.1

# randomization:
#   drone:
#     train:
#       mass_scale: [1.0, 1.0]
#       inertia_scale: [1.0, 1.0]
#       c_tf_scale: [1.0, 1.0]
#       com: [0.0, 0.0] 
# payload_mass_scale: [1., 1.] 
# bar_length: 1.0

rwd_gains:
  rwd_k_exp: 7.
  Cy: 3.0
  Cy_dot: 1.5
  Cq: 1.0
  Cw: 0.5
  Cb1: 1.0
  CR: 1.0
  CW: 0.5
  CIy: 0.
  CIb1: 0.
  rwd_alpha: 0.01
  rwd_beta: 0.05

inverted_pendulum: true
payload_radius: 0.05
payload_mass: 0.05
drone_scale: 1.35

push_force_scale: [0., 0., 0.]
push_interval: 0.

action_transform: null